### ISSUE TITLE
No response when Account number is wrong

### ISSUE THREAD

**Issue by obinnanwamuo0** [olakunlevpn/Nigeria-Bank-Account-Number-API#1]
Hi, and thank you for this api. it came in very handy but i have a issue when i input a wrong account number. there is no response. can this be resolved? 

Thank you in advance

**Comment by obinnanwamuo0** [comment]
Hi kunle, it's still the same. i tried selecting a bank with a wrong account number but returned empty response

**Comment by olakunlevpn** [comment]
I will check for bugs and improve the code quality soon on my free time.

**Comment by olakunlevpn** [comment]
Hello, the issue has been resolved, regards

**Comment by obinnanwamuo0** [comment]
hello ola,
Wonderful job. it worked but one little issue that recently just popped up
was that i'm getting a "Not secured connection" which returns a CORS Error.
Could this be rectified. my application depends on your api for retrieving
account details. looking forward to your response

**Comment by olakunlevpn** [comment]
Hello,  I just test out the API and we dont get such error from out end, can you provide me with more details about this  ?

**Comment by olakunlevpn** [comment]
Yes
________________________________
